# Generated by Django 5.1.6 on 2025-03-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_finalappointmentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctortype',
            name='specialization',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
